spring:
  main:
    banner-mode: off
  application:
    name: study-devops-spring
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

logging:
  level:
    com:
      chassot: DEBUG
  file:
    path: logs

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always

custom:
  valueTest: hello
  valueDebug: world
  database:
    password: dGVzdA==