apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-namespace-reader-role
  labels:
    {{- include "chart.labels" . | indent 4 }}
    {{- include "common.labels" . | indent 4 }}
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-namespace-reader-role-binding
  labels:
    {{- include "chart.labels" . | indent 4 }}
    {{- include "common.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Release.Name }}-namespace-reader-role
  apiGroup: ""