apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | indent 4 }}
    {{- include "common.labels" . | indent 4 }}
data:
  custom.database.password: {{ .Values.custom.database.password }}