apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-service
  labels:
    {{- include "chart.labels" . | indent 4 }}
    {{- include "common.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.application.service.port }}
    targetPort: {{ .Values.application.pod.container.port }}
  selector:
    {{- include "common.labels" . | indent 4 }}